# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.1a1.dev2+g2474d85.d20230901'
__version_tuple__ = version_tuple = (0, 0, 1, 'dev2', 'g2474d85.d20230901')
