event_tag: Fuego2009
client: IRIS
client_debug: false
event_selection: default
seconds_before_event: 3600
seconds_after_event: 600
networks: XT
stations: F900,F9NW,F9NE
channels: HHE,HHN
locations: '*'
seconds_before_ref: 100
seconds_after_ref: 300
demean: false
detrend: false
remove_response: false
resample_freq: null
remove_clipped: true
remove_insufficient_length: true
remove_masked_data: true
write_files: inv,sac
plot_files: null
log_level: WARNING
